### ISSUE TITLE
No support for data URIs

### ISSUE THREAD

**Issue by sandstrom** [less/less.ruby#78] opened 2009-09-02 22:19 UTC
// ERROR

! Syntax Error: on line 1683: expected one of ) : got , after:

div.instruction::after {

  background-image:url(data:image/gif;base64

// CODE

background-image:url(data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAB0AAAAMCAYAAACeGbYxAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAJRJREFUeNpi/P//PwMMfNzaAebweXsyUAt82rodTPN7VzDCxJiQFcAkYAppYSGGpdS0GJeFWC2lhsX4LMSwFBinFFuMzUJkc7H6lBKLibEQZ/D+Z7hIssWEgpSgpaRajM1CkH5kM4iylFiLcVlIlk+JsZgcC0GAEa1EwqkQaDBGyUVMosGmn4nYrIAtVRNrIToACDAAFNdtvUcGQCoAAAAASUVORK5CYII=);

**Comment by sandstrom** [comment] 2009-09-02 22:20
http://en.wikipedia.org/wiki/Data_URI_scheme

**Comment by cloudhead** [comment] 2009-09-03 00:15
Duplicate of #71

**Closed as completed by cloudhead** 2009-09-03 00:15 UTC
