### ISSUE TITLE
wrong base64 image processing

### ISSUE THREAD

**Issue by antono** [less/less.ruby#105] opened 2009-10-16 02:23 UTC
hello, i have such string in my less:

background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABcAAAAXCAIAAABvSEP3AAAAdElEQVQ4jaXTuw0AIQwDUHNLZP/tkim4BgmBQr6urSc3HswML0RkF74+ISKOEiGcLUHCUuLEU0kRupIlFKVA3EqNOJQysZUOsZQmAWDMOZsE3B9FCCKylCBhbYkTTyVF6EqWUJQCcSs14lDKxFY6xFKaBIAfr0VH4jmCqdkAAAAASUVORK5CYII%3D);

Less parser adds whitespace after "data:image/png;base64,". image will not be decoded by browsers.

**Comment by cloudhead** [comment] 2009-10-16 02:48
duplicate of http://github.com/cloudhead/less/issues#issue/71, use "" around the url for now.

**Closed as completed by cloudhead** 2009-10-16 02:48 UTC
